"""
Central configuration for the MedCare inventory decision-support system.

Every constant that more than one module needs lives here.
Business logic must read from this file instead of hard-coding values.
"""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd

# ------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent

DATA_DIR = BASE_DIR / "data"
# Ayush's original demand file (2025-09-23 .. 2026-09-22, from data/medcare_mysql.sql). Never modified.
SOURCE_DEMAND_CSV = DATA_DIR / "demand.csv"
# Date-shifted simulation copy, generated by database/simulation_data.py.
# This is the demand file the database loads.
SIMULATION_DEMAND_CSV = DATA_DIR / "derived" / "demand_simulation.csv"
SIMULATION_DEMAND_METADATA = DATA_DIR / "derived" / "demand_simulation_metadata.json"
DEMAND_CSV = SIMULATION_DEMAND_CSV
# Sales data (E1 operational consumption). Source file is never modified;
# the database loads the date-shifted simulation copy.
SOURCE_SALES_CSV = DATA_DIR / "sales.csv"
SIMULATION_SALES_CSV = DATA_DIR / "derived" / "sales_simulation.csv"
SIMULATION_SALES_METADATA = DATA_DIR / "derived" / "sales_simulation_metadata.json"
INVENTORY_CSV = DATA_DIR / "inventory.csv"
BATCHES_CSV = DATA_DIR / "batches.csv"

SCHEMA_PATH = BASE_DIR / "database" / "schema.sql"                        # Ayush's tables
SCHEMA_EXTENSIONS_PATH = BASE_DIR / "database" / "schema_extensions.sql"  # E1 tables
DATABASE_PATH = Path(
    os.environ.get("MEDCARE_DB_PATH", BASE_DIR / "database" / "medcare.db")
)

OUTPUT_DIR = BASE_DIR / "outputs"
FORECAST_OUTPUT_CSV = OUTPUT_DIR / "forecast_output.csv"
FORECAST_METADATA_JSON = OUTPUT_DIR / "forecast_metadata.json"
TRANSACTION_LOG_CSV = OUTPUT_DIR / "transaction_log.csv"
SIMULATED_INVENTORY_CSV = OUTPUT_DIR / "simulated_inventory_daily.csv"
NOTIFICATION_LOG_CSV = OUTPUT_DIR / "notification_log.csv"
SEASONAL_SIGNAL_CSV = OUTPUT_DIR / "seasonal_demand_signal.csv"
SIMULATION_SUMMARY_JSON = OUTPUT_DIR / "simulation_summary.json"
SIMULATION_PURCHASE_ORDERS_CSV = OUTPUT_DIR / "simulation_purchase_orders.csv"

# ------------------------------------------------------------------
# Simulated timeline
# ------------------------------------------------------------------
# The system behaves as if "today" is SIMULATION_DATE:
#   history  = demand on or before SIMULATION_DATE
#              (2025-10-01 .. 2026-09-30 in the date-shifted simulation copy)
#   forecast = the FORECAST_HORIZON_DAYS days after SIMULATION_DATE
#              (2026-10-01 .. 2026-10-30)
# Ayush's source demand (2025-09-23 .. 2026-09-22) is shifted by a constant
# number of days so that it ends on SIMULATION_DATE (see database/simulation_data.py).

SIMULATION_DATE = "2026-09-30"
FORECAST_HORIZON_DAYS = 30


def simulation_timestamp() -> pd.Timestamp:
    """SIMULATION_DATE as a normalised pandas Timestamp (raises on a bad value)."""
    ts = pd.Timestamp(SIMULATION_DATE)
    if pd.isna(ts):
        raise ValueError(f"Invalid SIMULATION_DATE: {SIMULATION_DATE!r}")
    return ts.normalize()


# ------------------------------------------------------------------
# Forecasting model (Nishit's Chronos-2 setup)
# ------------------------------------------------------------------

CHRONOS_MODEL_NAME = os.environ.get("MEDCARE_CHRONOS_MODEL", "amazon/chronos-2")
CHRONOS_DEVICE = os.environ.get("MEDCARE_CHRONOS_DEVICE", "cpu")

# Minimum history Nishit's predict.py required before forecasting.
MIN_HISTORY_DAYS = 14

# Covariates passed to Chronos-2 (past values + carried-forward future values).
COVARIATE_COLUMNS = ["promotion_flag", "season_flag"]

# Future promotion/season calendars do not exist in the source data.
# Nishit's fallback: carry forward the most recent known flag values.
# This is a documented limitation, not a real business signal.
FUTURE_COVARIATE_STRATEGY = "carry_forward"

# Quantile used as the point forecast (median).
POINT_FORECAST_QUANTILE = 0.5

# Number of series sent to Chronos-2 per predict() call in batch mode.
FORECAST_BATCH_SIZE = 64

# ------------------------------------------------------------------
# Decision-engine thresholds (used from Phase 5 onwards)
# ------------------------------------------------------------------

RISK_HIGH = "HIGH"
RISK_MEDIUM = "MEDIUM"
RISK_LOW = "LOW"
RISK_LEVELS = (RISK_HIGH, RISK_MEDIUM, RISK_LOW)

# Decimal places used when reporting calculated quantities.
REPORT_DECIMALS = 2

# Batch expiry classification (days_to_expiry = expiry_date - SIMULATION_DATE):
#   < 0     -> EXPIRED
#   0..30   -> NEAR_EXPIRY
#   31..60  -> EXPIRING_SOON
#   > 60    -> NORMAL
# Calendar labels only. Operationally a batch is usable only if
# expiry_date > SIMULATION_DATE (the simulation date is the END of the day).
NEAR_EXPIRY_DAYS = 30
EXPIRING_SOON_DAYS = 60

# SIMULATION ASSUMPTION, not source data: the datasets have no inter-warehouse
# transit time, and supplier lead_time_days must NOT be used for transfers.
# A batch can be transferred only if it is still usable after arriving:
#     days_to_expiry > TRANSFER_TRANSIT_DAYS
TRANSFER_TRANSIT_DAYS = 2

BATCH_EXPIRED = "EXPIRED"
BATCH_NEAR_EXPIRY = "NEAR_EXPIRY"
BATCH_EXPIRING_SOON = "EXPIRING_SOON"
BATCH_NORMAL = "NORMAL"

# ------------------------------------------------------------------
# E1 operational simulation (sales / receipts / adjustments)
# ------------------------------------------------------------------
# Default length of the forward simulation (days after SIMULATION_DATE).
E1_SIMULATION_DAYS = FORECAST_HORIZON_DAYS

# Requested sales for simulated day d = units_sold on the same day one year
# earlier (d - 365) in the derived sales history, scaled per item:
#   "demand_calibrated": x (mean demand_qty / mean units_sold) for that item.
#       sales.csv volumes are ~2.8x demand.csv, while stock and thresholds
#       are sized to demand; calibration keeps the sales day-to-day pattern
#       (weekday, price/promo dips) at the demand scale.
#   "raw": units_sold unchanged (stress test; most items stock out within days).
SALES_SIMULATION_SCALING = "demand_calibrated"
SALES_LOOKBACK_DAYS = 365

# Replenishment during the E1 operational simulation (python main.py simulate):
#   "plan+reorder_point" (DEFAULT): execute the Phase 9 P1 plan made on
#       SIMULATION_DATE, and during the simulation apply the E1 reorder-point
#       rule each day: if usable + on-order <= min_threshold, order
#       ceil(min_threshold + avg_daily_demand x lead_time) - (usable + on-order),
#       received after lead_time_days. These are OPERATIONAL reorders labelled
#       E1_OPERATIONAL_REORDER. They are not part of the P1 recommendation and
#       never change the Phase 9 decision engine.
#   "plan-only": execute only the P1 plan (comparison/testing). "plan" is an alias.
E1_REPLENISHMENT_POLICY = "plan+reorder_point"

# SIMULATION ASSUMPTION, not source data: batch expiry for supplier receipts.
# The data has no shelf-life information; this only needs to exceed the
# simulation window so new supplier stock does not expire inside it.
SUPPLIER_RECEIPT_SHELF_LIFE_DAYS = 365

# ------------------------------------------------------------------
# Seasonal demand signal (P1 demand sensing; not an influenza model)
# ------------------------------------------------------------------
# Analog window = the forecast window shifted back one year.
#   ELEVATED : season_flag active on >= SEASON_ACTIVE_SHARE of analog days AND
#              analog demand >= (1 + SEASON_ELEVATED_UPLIFT) x the item's average
#   SEASONAL : season_flag active on >= SEASON_PRESENT_SHARE of analog days
#   NORMAL   : otherwise
SEASON_ACTIVE_SHARE = 0.5
SEASON_PRESENT_SHARE = 0.2
SEASON_ELEVATED_UPLIFT = 0.05
SEASON_SIGNAL_NORMAL = "NORMAL"
SEASON_SIGNAL_SEASONAL = "SEASONAL"
SEASON_SIGNAL_ELEVATED = "ELEVATED"

# ------------------------------------------------------------------
# Notifications (credentials ONLY from environment variables)
# ------------------------------------------------------------------
#   MEDCARE_NOTIFICATION_MODE = outbox | email | auto   (default: outbox)
#     outbox : record every notification, never send (status OUTBOX)
#     email  : send via SMTP; invalid/missing settings raise an error
#     auto   : send if SMTP settings are complete, otherwise record as OUTBOX
#   SMTP_HOST, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD, ALERT_EMAIL_TO,
#   ALERT_EMAIL_FROM (optional, defaults to SMTP_USERNAME), SMTP_USE_TLS (default true)
NOTIFICATION_MODE_ENV = "MEDCARE_NOTIFICATION_MODE"
DEFAULT_NOTIFICATION_MODE = "outbox"
NOTIFY_ALERT_TYPES = ("STOCKOUT_RISK_HIGH", "E1_THRESHOLD", "EXPIRY_RISK_HIGH", "REORDER_RECOMMENDED")
